### ISSUE TITLE
openapi.yaml odd renderings

### ISSUE THREAD

**Issue by gridworkz** [Qovery/qovery-client-go#6]
Lines: 1367 and 1410 in the openapi.yaml file are rendered strangely. 

```
$ref: '#/paths/~1organization~1%7BorganizationId%7D~1cluster~1%7BclusterId%7D~1advancedSettings/put/requestBody/content/application~1json/schema'
```
```
$ref: '#/paths/~1organization~1%7BorganizationId%7D~1cluster~1%7BclusterId%7D~1advancedSettings/put/requestBody/content/application~1json/schema'
```
It appears the resource: ClusterAdvancedSettings is not rendering in components: section either.

Also on line: 11678:
```
    CluserCredentials:
      properties:
        name:
          type: string
        access_key_id:
          type: string
        secret_access_key:
          type: string
      required:
      - name
      type: object
```
There's an extra ClusterCredentials entry but spelled CluserCredentials.

**Comment by benamib** [comment]
Hello @gridworkz 

Thank you for reporting this, it should have been fixed now. 
We updated our github actions on the [qovery-openapi-spec](https://github.com/Qovery/qovery-openapi-spec) to avoid having this kind of issues again. 

Let us know if it works for you now

**Comment by gridworkz** [comment]
Yep, all good now. Thx.
